name: 'externals'

type: 'php:7.1'
build:
    flavor: composer

runtime:
    extensions:
        - newrelic
        -
            name: 'blackfire'
            configuration:
                server_id: '69b9589f-b986-4d85-af21-cb8cedd55389'
                server_token: 'e8de86bb7a3c8d10975ba4143c31193cee56742718dc34296d513a94f7473125'

dependencies:
    nodejs:
        bower: "^1.8"

# The hooks that will be triggered when the package is deployed.
hooks:
    # Build hooks can modify the application files on disk but not access any services like databases.
    build: |
        bower install --production --allow-root

# The size of the persistent disk of the application (in MB).
disk: 2048

# The mounts that will be performed when the package is deployed.
mounts:
    "/var/cache": "shared:files/cache"
    "/var/log": "shared:files/log"

relationships:
    database: "database:mysql"

web:
    locations:
        '/':
            # The public directory of the application relative to its root.
            root: 'web'
            # The front-controller script which determines where to send
            # non-static requests.
            passthru: '/index.php'
        # Allow uploaded files to be served, but do not run scripts.
        # Missing files get mapped to the front controller above.
#        '/files':
#            root: 'web/files'
#            scripts: false
#            allow: true
#            passthru: '/index.php'
